### ISSUE TITLE
Server error on latest release

### ISSUE THREAD

**Issue by sternschnaube** [G4me4u/g4mespeed#11]
When I stop the server:

Exception stopping the server
java.lang.RuntimeException: java.io.IOException: No such file or directory
	at com.g4mesoft.setting.GSSettingManager.saveSettings(GSSettingManager.java:162) ~[g4mespeed-1.4.6-mc1.21.jar:?]
	at com.g4mesoft.core.GSController.onStop(GSController.java:64) ~[g4mespeed-1.4.6-mc1.21.jar:?]
	at com.g4mesoft.core.server.GSServerController.onStop(GSServerController.java:95) ~[g4mespeed-1.4.6-mc1.21.jar:?]
	at com.g4mesoft.core.server.GSServerController.onServerShutdown(GSServerController.java:162) ~[g4mespeed-1.4.6-mc1.21.jar:?]
	at net.minecraft.server.MinecraftServer.handler$fhf000$g4mespeed$onShutdown(MinecraftServer.java:16213) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:637) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:561) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:735) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method) ~[?:?]
	at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258) ~[?:?]
	at java.base/java.io.File.createNewFile(File.java:1045) ~[?:?]
	at com.g4mesoft.util.GSFileUtil.ensureFileExists(GSFileUtil.java:27) ~[g4mespeed-1.4.6-mc1.21.jar:?]
	at com.g4mesoft.util.GSFileUtil.writeFile(GSFileUtil.java:53) ~[g4mespeed-1.4.6-mc1.21.jar:?]
	at com.g4mesoft.setting.GSSettingManager.saveSettings(GSSettingManager.java:158) ~[g4mespeed-1.4.6-mc1.21.jar:?]
	... 9 more

**Comment by G4me4u** [comment]
Thank you for the report! Does this happen on every shutdown or did it just happen once?

**Comment by sternschnaube** [comment]
Every shutdown.

**Comment by G4me4u** [comment]
Interesting - it seems to be related to creating the settings file (just the file itself, not the data) before the game starts. Can I see the logs of it starting? I only need to see the lines starting with "Unable to load settings file". I'd like to see the nature of the path.

**Comment by sternschnaube** [comment]
https://pastebin.com/raw/uF15Qa0m

**Comment by G4me4u** [comment]
Well I purposefully did not log the path, but it seems that redstone multimeter has the same issue. It seems it does not resolve the working directory properly. Admittedly I should encapsulate the thing with a try catch so it does not crash but then we would not have found the issue.

I'll fix it as soon as I have time. I apologize for the delay.

You can report this issue to Redstone Multimeter as well. In the log you can see it fails to load and save the config.

**Comment by G4me4u** [comment]
Fixed in latest release (v1.4.8)

**Comment by sternschnaube** [comment]
Thanks 😄
